var ccb_resources = [
    {type:'image', src:"ccbResources/common2.png"},
    {type:'image', src:"ccbResources/ccbDefaultImages.png"},
    {type:'image', src:"clickme.png"},
    {type:'ccbi', src:"MainScene.ccbi"},
    {type:'ccbi', src:"RoomItem.ccbi"},
    {type:'plist', src:"ccbResources/common.plist"},
    {type:'ccbi', src:"HallScene.ccbi"},
    {type:'image', src:"clickme-down.png"},
    {type:'image', src:"ccbResources/ccbParticleSmoke.png"},
    {type:'ccbi', src:"LandingScene.ccbi"},
    {type:'image', src:"ccbResources/biankuang_9.9.png"},
    {type:'ccbi', src:"Menu.ccbi"},
    {type:'image', src:"ccbResources/common.png"},
    {type:'image', src:"ccbResources/ccbParticleSnow.png"},
    {type:'ccbi', src:"AboutScene.ccbi"},
    {type:'plist', src:"ccbResources/landing.plist"},
    {type:'image', src:"ccbResources/ccbParticleStars.png"},
    {type:'image', src:"ccbResources/touxiang01.png"},
    {type:'image', src:"ccbResources/landing.png"},
    {type:'plist', src:"ccbResources/hall.plist"},
    {type:'ccbi', src:"ProgressScene.ccbi"},
    {type:'plist', src:"ccbResources/common2.plist"},
    {type:'image', src:"ccbResources/ccbParticleFire.png"},
    {type:'plist', src:"ccbResources/ccbDefaultImages.plist"},
    {type:'image', src:"ccbResources/hall.png"},
];
