var ccb_resources = [
    {type:'ccbi', src:"MainScene.ccbi"},
    {type:'plist', src:"ccbResources/ccbDefaultImages.plist"},
    {type:'image', src:"ccbResources/landing.png"},
    {type:'ccbi', src:"LandingScene.ccbi"},
    {type:'image', src:"ccbResources/ccbDefaultImages.png"},
    {type:'plist', src:"ccbResources/landing.plist"},
    {type:'image', src:"ccbResources/ccbParticleFire.png"},
    {type:'image', src:"clickme.png"},
    {type:'image', src:"ccbResources/ccbParticleStars.png"},
    {type:'ccbi', src:"ProgressScene.ccbi"},
    {type:'ccbi', src:"HallScene.ccbi"},
    {type:'image', src:"clickme-down.png"},
    {type:'image', src:"ccbResources/ccbParticleSmoke.png"},
    {type:'image', src:"ccbResources/ccbParticleSnow.png"},
];
