APP_STL := gnustl_static
#APP_CPPFLAGS := -frtti -DCOCOS2D_DEBUG=1
#APP_CPPFLAGS := -DCOCOS2D_DEBUG=1 -D__GXX_EXPERIMENTAL_CXX0X__ -std=c++11 -frtti -Wno-error=format-security -fsigned-char -Os $(CPPFLAGS)

APP_PLATFORM := android-8

APP_CPPFLAGS := -frtti -std=c++11 -Wno-error=format-security -Wno-literal-suffix -Wno-deprecated-declarations -fsigned-char -Os $(CPPFLAGS)
APP_DEBUG := $(strip $(NDK_DEBUG))
ifeq ($(APP_DEBUG),1)
  APP_CPPFLAGS += -DCOCOS2D_DEBUG=1
  APP_OPTIM := debug
else
  APP_CPPFLAGS += -DNDEBUG
  APP_OPTIM := release
endif
#APP_ABI := armeabi


ifeq ($(DDZ_DEBUG),1)
  APP_CPPFLAGS += -DDDZ_DEBUG=1
else
  APP_CPPFLAGS += -DDDZ_DEBUG=0
endif



CC_CURL_ENABLED := 1
APP_CPPFLAGS += -DCC_CURL_ENABLED=1

CC_JPEG_ENABLED := 1
APP_CPPFLAGS += -DCC_JPEG_ENABLED=1

CC_TIFF_ENABLED := 1
APP_CPPFLAGS += -DCC_TIFF_ENABLED=1

CC_WEBP_ENABLED := 1
APP_CPPFLAGS += -DCC_WEBP_ENABLED=1

CC_PHYSICS_ENABLED := 1
APP_CPPFLAGS += -DCC_PHYSICS_ENABLED=1

CC_SQLITE_ENABLED := 1
APP_CPPFLAGS += -DCC_SQLITE_ENABLED=1
APP_CFLAGS += -DCC_SQLITE_ENABLED=1

CC_CCSTUDIO_ENABLED := 1
APP_CPPFLAGS += -DCC_CCSTUDIO_ENABLED=1

CC_CCB_ENABLED := 1
APP_CPPFLAGS += -DCC_CCB_ENABLED=1

CC_DRAGONBONES_ENABLED := 1
APP_CPPFLAGS += -DCC_DRAGONBONES_ENABLED=1

CC_FILTERS_ENABLED := 1
APP_CPPFLAGS += -DCC_FILTERS_ENABLED=1
